name: EFFENAF.
favicon: null
layout_spectrum: 0.09633604157716036
typography_spectrum: 0.2370720598846674
title: Doorgronden Positioneren Verbeelden
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f0000'
    - '#ff9300'
    - '#00ff01'
    - '#0065de'
  brandStrength: 0.8342436880338937
  lightness: 0.9237540238536894
  saturation: 0.9498027828522027
  rhythmicContrast: 0.9270797676872462
purpose: []
